Text format from "send" to "open"
common-workflow-language/user_guide pull request #302
Opened 2022-10-15 20:51 UTC by Fienne

Changed the "send a pull request" to "open a pull request" because it is a better way of saying it and most users understand it better this way.

2022-10-15 21:05 UTC, kinow commented on src/topics/yaml-guide.md
> +where whitespace after the `:` is optional, but is required when defining fields in a CWl file.
s/CWl/CWL

2022-10-17 08:08 UTC, mr-c requested changes

2022-10-17 08:08 UTC, mr-c commented on src/tutorials.md
>  if you would like to add another tutorial to the list.
Thanks for bring my attention to this text.

```suggestion
This is a list of tutorials provided by the CWL community. Use the `Edit this page` link in the menu if you would like to add another tutorial to the list.
```

This is more straightforward, than sending readers to the GitHub hosted repository without showing them which file to edit.

FYI: Some communities don't use social coding services like GitHub, so pull requests (or even the patches themselves) are **sent** via email.

2022-10-17 13:10 UTC, mr-c approved these changes

2022-10-17 13:13 UTC, merged